name: Process dataset 

on: 
  workflow_dispatch:
    inputs: 
      dataset-folder:
        description: "Enter the relative path to the new dataset"
        required: true

jobs: 
  process_dataset: 
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v3
      - name: Run process-dataset script
        env:
          NODE_ENV: "staging"
          STAGING_FIREBASE_TOKEN: ${{ secrets.STAGING_FIREBASE_TOKEN }}
        run: npm run process-dataset -- "${{ github.event.inputs.dataset-folder }}"
