name: Publish dataset to production DB

on:
  workflow_dispatch:
    branches: 
      - main
    inputs: 
      dataset-folder:
        description: "Enter the relative path to the new dataset"
        required: true

jobs: 
  release_dataset: 
    name: Release Dataset
    runs-on: ubuntu-latest
    env:
      NODE_ENV: "production"
      FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: npm ci
      - name: Run release-dataset script
        env: 
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: npm run release-dataset -- "${{ github.event.inputs.dataset-folder }}"